### ISSUE TITLE
The GUI insert plugin should close upon insertion

### ISSUE THREAD

**Issue by nkoenig** [ignitionrobotics/ign-gazebo#176] opened 2020-06-03 22:20 UTC
When inserting a GUI plugin, the menu stays open and the user has to click somewhere else to close the menu. I think the menu should close when a plugin is inserted.

**Comment by chapulina** [comment] 2020-06-03 22:28
This is a duplicate of https://github.com/ignitionrobotics/ign-gui/issues/37

@Sarath18 fixed that for Dome on https://github.com/ignitionrobotics/ign-gui/pull/60

We could backport it to Blueprint (`ign-gui2`) and Citadel (`ign-gui3`)

**Closed by chapulina** 2020-06-03 22:28 UTC
Labels: GUI, enhancement
