### ISSUE TITLE
JointPositionControllerGui Test Failing (Ignition Fortress)

### ISSUE THREAD

**Issue by ibrahiminfinite** [ignitionrobotics/ign-gazebo#890] opened 2021-06-28 04:56 UTC
## Environment
* OS Version: Ubuntu 20.04 
* Source build : latest commit #877 

      - [ x] running on real hardware

  
## Description
* Expected behavior:  All tests should pass
* Actual behavior: JointPositionControllerGui  test fails

## Steps to reproduce

1. Build ignition fortress from source 
2. Run  JointPositionControllerGui test

Console output : 
```
[GUI] [Wrn] [Application.cc:657] [QT] file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
[GUI] [Wrn] [Application.cc:657] [QT] file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain", "applicationName")
[GUI] [Wrn] [Application.cc:657] [QT] file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
[GUI] [Wrn] [Application.cc:657] [QT] file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain", "applicationName")
```

Note  : 

The execution seems to get stuck when requesting the state and the GUI stops responding
```C++
  // Request state again, do it in separate thread so we can call processEvents
  std::thread waiting([&]()
  {
    runner->RequestState();
  });
```

Image : 
![image](https://user-images.githubusercontent.com/12377945/123582276-2ad07600-d7fb-11eb-8d9c-1c7bcc340624.png)

**Comment by chapulina** [comment] 2021-11-17 00:37
I can't reproduce this test failure anymore locally and it seems to be passing consistently on CI:

https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo6-bionic-amd64/22/testReport/(root)/JointPositionControllerGui/history/

Closing this issue, please reopen if the test starts failing again.

**Closed by chapulina** 2021-11-17 00:37 UTC
Labels: bug, GUI, tests
