### ISSUE TITLE
Add image snapshot to GUI

### ISSUE THREAD

**Issue by nkoenig** [ignitionrobotics/ign-gazebo#448] opened 2020-11-04 17:39 UTC
It would be nice to port image snapshot from Gazebo classic to Ignition Gazebo. The basic functionality is: click a button and an image of the current 3D scene is generated.

**Comment by chapulina** [comment] 2020-11-04 17:43
I think this is a duplicate of https://github.com/ignitionrobotics/ign-gui/issues/95, I'll close this one and future comments can go there.

**Closed by chapulina** 2020-11-04 17:43 UTC
Labels: GUI, close the gap, good first issue
